### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by InvictusMB**
**What**:

Do not run release step on Windows
Skip Windows CI step if build is not invoked for PR

**Why**:

[Known issue](https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264) with Travis secrets 

**How**:

Skip Windows job if the build is not executed for a PR as it would fail anyway

### CODE REVIEW

**Comment by InvictusMB** [comment]
Now it does not run Windows stage at all.
Will figure this one out later. Please do not merge yet.

**Comment by InvictusMB** [comment]
OK, this seems to run properly on PRs now.
Please merge and let's check if the Windows job is skipped for master.

**Comment by InvictusMB** [comment]
It's a pity you can not detect the presence of the secrets.
`if: env(GH_TOKEN) IS NOT present` always evaluates to `false` and `if: env(GH_TOKEN) IS present` is always `true` no matter if the execution environment actually exposes it to you.
It is likely to be a Travis CI bug.

`if: fork = false` also seems to be `true` even though the build is run for the PR coming from a fork.

I eventually had to settle with the ugliest option:
`if: head_repo != "kentcdodds/babel-plugin-macros"`
I hope it works as expected after the PR is merged. Otherwise the whole Windows thing has to be allowed to fail or dropped entirely.

**Comment by kentcdodds** [comment]
Thank you very much!

**Comment by InvictusMB** [comment]
It still fails. I guess the `head_repo` is not populated outside of PR builds and the check is not sufficient for builds on master. Otherwise I don't see why the equality check would give a false positive.

This line suggests that it should work the way I expect:
https://github.com/travis-ci/travis-conditions/blob/e1466fe0a3a44604f6c3cf88f12f27bfbf0a0552/spec/v1/fixtures/passes.txt#L637

I assume if `repo = head_repo` is supposed to detect CI runs inside the same repository then `head_repo` should always be populated. Therefore `repo != head_repo` should also detect PRs coming from forks.

I will try that later.

Maybe I could also filter by `type = pull_request`. I have to think a bit more about this option.

**Comment by kentcdodds** [comment]
Would it improve things to make kcd-scripts not run the Travis script on Windows? That might be easier.

**Comment by InvictusMB** [comment]
No, that would not help. The root cause is that Windows container itself halts as soon as there are any secret environment variables set. No matter what scripts are run inside. 
This does not happen with PRs as your secrets are not exposed to PR builds.
So the build has to be avoided in Travis config before any containers are instantiated.

Another option is to allow the job to fail. But that kinda defeats the whole purpose of an automated test.

I'm sorry for breaking the master.

**Comment by kentcdodds** [comment]
No worries. I think the best thing to do from here is restore the original travis setup and add appveyor.

**Comment by InvictusMB** [comment]
I believe I've found a proper configuration. I did some tests on a dummy repo and this is the condition that works as expected: `if: type = pull_request AND head_repo != repo`

`if: head_repo IS present AND head_repo != repo` also works well but the intent is less explicit.

**Comment by kentcdodds** [comment]
Sounds great! Want to give that a try?

**Pull request merged**
