### PR TITLE
Revert d5d44a6 to fix regression

### LINKED ISSUE #164: "Duplicate declaration" error due to identifier traversal change
Hey Kent 👋 

I'm experiencing an import issue in twin.macro that's popped up in the latest version of babel-plugin-macros (v3.0.0).

I've tracked [down the change](https://github.com/kentcdodds/babel-plugin-macros/compare/v2.8.0...v3.0.0#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R235
) that's caused the break and noticed it wasn't described in the change list:

```diff
- state.file.scope.path.traverse({
+ traverse(state.file.ast, {
    Identifier() {},
})
```

It breaks with the following error:

```shell
./pages/index.tsx
TypeError: /Users/.../pages/index.tsx: Duplicate declaration "_styled" (This is an error on an internal node. Probably an internal error.)
```

The error hints at something else due to twin having inserted another `styled-components/macro` import. (A macro adding another macro ha!)

Here's the [code that inserts the import in twin.macro](https://github.com/ben-rogerson/twin.macro/blob/master/src/macro/css.js#L70):

```js
twinImportPath.insertBefore(
    t.importDeclaration(
      [t.importDefaultSpecifier(generateUid('cssPropImport', program))],
      t.stringLiteral(styledComponentsMacroImport)
    )
)
```

Reference issue: https://github.com/ben-rogerson/twin.macro/issues/241

### PR DESCRIPTION
**Pull request by conartist6**
Fixes #164, a regression of https://github.com/kentcdodds/import-all.macro/issues/7.

We need a test for the regression so that it doesn't break again, and (assuming this is still the right fix for the original issue) also we will have to find a different fix for the issue I have reopened, #121.

### CODE REVIEW

**Comment by ben-rogerson** [comment]
Hey Kent, it'd be awesome if you could patch this in - it'll fix some errors I'm seeing in twin.macro.

**Review by kentcdodds — APPROVED** [review]
Sorry, this feel through the cracks for me. Thanks!

**Comment by kentcdodds** [comment]
Oh, it's still a draft PR. I think @conartist6 wanted to write a regression test for it. @ben-rogerson world you like to help with that yourself?

**Comment by conartist6** [comment]
It's mergeable, with or without the regression test. The fact that every set of pushed changes is release though makes it harder for me to imagine that the test will be added in the future if it isn't added now.

**Comment by kentcdodds** [comment]
I definitely don't have time to add a test for it myself. I'm pretty much at the "quick review and merge if people say it's ok" stage of maintaining this package 😬 (https://kcd.im/no-time).

**Comment by conartist6** [comment]
@ben-rogerson Do you mind contributing that fix? I may have time to do it over the next few days, but also I may not. You're the only one who seems to be directly affected by the possibility of a regression. If you'd rather just get the fix in now, I'm fine with that.

**Comment by kentcdodds** [comment]
We don't have many changes in this repo, so I think I'll go ahead and merge this now. @ben-rogerson if you'd like to make sure this never breaks in the future, please contribute a test. Thanks!

**Pull request merged**
